# Site
repository: sproogen/resume-theme
favicon: images/t1.ico

# Content configuration version
version: 2

# Personal info
name: Maxime Nederkorn
title: Computer Science MSc.
email: mail@nederkorn.xyz
website: www.nederkorn.xyz

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  mnederkorn
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0002-8807-7074

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
# about_profile_image: images/profile.jpg
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Maxime and I'm a computer science graduate. I'm currently looking for a software development job in and around Amsterdam.

  I am most proficient in <mark>python</mark> and I prefer to work on the more abstract aspects of software development in the direction of data science or machine learning.

  My native languages are german and french and I speak english fluently.

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Duisburg-Essen
        caption: 2013 - 2018
        sub_title: Bachelor of Applied Computer Science
        description: |
          The final thesis was *Computing Core Graphs with SAT/SMT Solvers* and deals with solving a problem from graph theory/theoretical computer science in practice. [The accompanying software](https://github.com/mnederkorn/CoReS) made heavy use of <mark>python</mark>.
          [A presentation](https://link.springer.com/chapter/10.1007/978-3-319-92991-0_3) based on this software was held at the *ICGT 2018* conference.
      - layout: left
        title: University of Duisburg-Essen
        caption: 2018 - 2023
        sub_title: Master of Applied Computer Science
        description: |
          As part of my master's I did a group project related to autonomous driving. We combined data from cameras and a Lidar to track other drivers in 3D space. The image processing for that used <mark>PyTorch</mark> and <mark>TensorFlow</mark> to detected the other drivers.

          I took an elective course on *bayesian modeling* where I learned various data processing and modelling techniques in <mark>R</mark> and <mark>stan</mark>.

          The final thesis was *Graph Games: Solutions and Strategy Computation in Theory and Practice*. Again, this deals with solving a problem from graph theory/theoretical computer science. For multiple related problems I took preexisting theoretical approaches and implemented them and tested their performance against each other under multiple conditions.
  - title: Work Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Duisburg-Essen
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Scientific research assistant
        caption: 2018 - 2019
        description: | # this will include new lines to allow paragraphs
          Based on the presentation we did going off of my Bachelor's thesis, the theoretical computer science chair hired me to expand [the software](https://github.com/mnederkorn/CoReS) to hypergraphs and add two ([1](https://github.com/mnederkorn/ccq), [2](https://github.com/mnederkorn/inv_chk)) proof of concept implementations that make use of the software. [This was again published](https://www.sciencedirect.com/science/article/abs/pii/S2352220818301561?via%3Dihub) in the *Journal of Logical and Algebraic Methods in Programming*.
      - layout: left
        title: various
        # link: boringcompany.com
        # link_text: boringcompany.com
        # sub_title: Scientific research assistant
        caption: 2013 - 2019
        description: | # this will include new lines to allow paragraphs
          Throughout my Bachelor's and part of my Master's I also worked various other jobs unrelated to software development or computer science: In electronics retail, as a bouncer, but for the most time as an employee for a private security contractor.
  - title: More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Beyond my typical developer hobbies like endless small programming projects and a liking for gaming, some of my other interests are powerlifting, crochet and outdoor sports like hiking/camping, biking and swimming. At my home in Germany I used to be a volunteer rescure swimmer with the Red Cross. When I have time I also play the piano and clarinet; I like jazz and classical music. I like to learn languages.

# Footer
# footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
